---
#- name: First add users to admin node as root
#  hosts: admin
#  remote_user: root

#  roles: 
#  - { role: ansible-role-users, tags: [ 'users', 'admin-users', 'user' ] }

- name:  Configure Admin Node
  hosts: ohpc_admin_nodes
  become: yes

  roles:
#  - { role: watermark-release, tags: [ 'always' ] } 
  - { role: ansible-role-fgci-repo, tags: [ 'fgci7', 'repos' ] }
  - { role: dns, tags: [ 'dns' ] }
  - { role: ansible-role-yum, tags: [ 'yum', 'repos' ] }
  - { role: ansible-role-ohpc-repo, tags: [ 'yum', 'repos', 'ohpc' ] }
  - { role: network_interface, tags: [ 'network' ],
    when: internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: ip_forwarder, tags: [ 'network' ],
    when: internal_interface is defined and
          external_interface is defined and
          internal_net is defined and
          internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: ansible-role-hosts-int, tags: [ 'hosts'] }
  - { role: ansible-role-ferm-firewall, tags: [ 'firewall', 'network' ] }
  - { role: ansible-role-chrony, tags: [ 'ntp', 'chrony' ] }
  - { role: ansible-role-yum-cron-2, tags: [ 'yumcron' ] }
  - { role: ansible-role-rsyslog, tags: [ 'rsyslog' ] }
  - { role: ansible-role-aliases, tags: [ 'aliases', 'email' ] }
  - { role: ansible-role-adauth, tags: [ 'auth' ] }
  - { role: ansible-role-sshd, tags: [ 'sshd', 'ssh' ] }
  - { role: ansible-role-smartd, tags: [ 'smartd' ] }
  - { role: ansible-role-dell, tags: [ 'dell' ] }
  - { role: ansible-role-rdma, tags: [ 'rdma', 'infiniband' ] }
  - { role: ansible-role-postfix, tags: [ 'postfix', 'mail' ] }
  - { role: ansible-role-autofs, tags: [ 'autofs' ] }
  - { role: ansible-role-pdsh-genders, tags: [ 'pdsh', 'genders' ] }
  - { role: ansible-role-systemd-journal, tags: [ 'systemd', 'journal', 'journald' ] }
  - { role: ansible-role-slurm, tags: [ 'slurm' ] }
  - { role: ansible-role-ohpc-setup, tags: [ 'ohpc' ] }
  - { role: ansible-role-lustre_client, tags: [ 'lustre' ], when: lustre_client_enabled }

# Local addons to this playbook
#
#- import_playbook: admin_local_play.yml
                                      
