---
- name: Admin Node
  hosts: admin
  remote_user: root
#  sudo: yes

  roles: 
  - { role: ansible-role-fgci-admin, tags: [ 'admin' ] }
  - { role: network_interface, tags: [ 'network' ],
    when: internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: ip_forwarder, tags: [ 'network' ],
    when: internal_interface is defined and
          external_interface is defined and
          internal_net is defined and
          internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: dns, tags: [ 'dns' ] }
  - { role: ansible-role-ntp, tags: [ 'ntp' ] }
  - { role: ansible-role-yum-cron, tags: [ 'yumcron' ] }
  - { role: ansible-role-users, tags: [ 'users' ] }
  - { role: ansible-role-rsyslog-client, tags: [ 'rsyslog-client' ] }
