---

# http://serverfault.com/questions/638507/how-to-access-host-variable-of-a-different-host-with-ansible
# We need some facts from the install node, specifically to find address of slurm controller.
- name: grab facts from install nodes
  hosts: production
  strategy: free
  tasks: [ ]

- name: Compute Nodes
  hosts: compute
  strategy: free
  remote_user: root
  become: yes

  pre_tasks:
    - name: Configure a cronjob for ansible-pull
      cron: name='ansible-pull' user=root
            job='/bin/nice /bin/bash /usr/local/bin/ansible-pull-script.sh >/var/log/ansible.log 2>&1'
            minute="{{ansible_pull_cron_minute_interval | default('0')}}"
            hour="{{ansible_pull_cron_hour_interval | default('*/2')}}"
            day="{{ansible_pull_cron_day_interval | default('*')}}"
            month="{{ansible_pull_cron_month_interval | default('*')}}"
            weekday="{{ansible_pull_cron_weekday_interval | default('*')}}"
            cron_file=ansible-pull
            state={{ansible_pull_cron_state | default('present')}}
      tags: pull

  roles: 
  - { role: watermark-release, tags: [ 'always' ]  } 
  - { role: ansible-role-fgci-repo, tags: [ 'fgci7', 'repos' ] }
  - { role: ansible-role-yum, tags: [ 'yum', 'repos', 'login' ] }
  - { role: ansible-role-ohpc-repo, tags: [ 'yum', 'repos', 'ohpc' ] }
  - { role: network_interface, tags: [ 'network' ] }
  - { role: ansible-role-hosts-int, tags: [ 'hosts'] }
  - { role: ansible-role-chrony, tags: [ 'ntp', 'chrony' ] }
  - { role: ansible-role-autofs, tags: [ 'autofs' ] }
  - { role: ansible-role-nis, tags: [ 'nis' ] }
  - { role: ansible-role-adauth, tags: [ 'auth' ] }
  - { role: ansible-role-pam, tags: [ 'auth', 'pam' ] }
  - { role: ansible-role-nsswitch, tags: [ 'nsswitch', 'auth' ] }
  - { role: ansible-role-yum-cron-2, tags: [ 'yumcron' ] }
  - { role: ansible-role-rsyslog, tags: [ 'rsyslog' ] }
  - { role: ansible-role-aliases, tags: [ 'aliases', 'email' ] }
  - { role: ansible-role-postfix, tags: [ 'postfix', 'mail' ] }
  - { role: ansible-role-idmapd, tags: [ 'idmapd' ] }
  - { role: ansible-role-nfs_mount, tags: [ 'nfsmount' ] }
  - { role: ansible-role-sshd-host-keys, tags: [ 'sshd', 'ssh', 'host-keys' ] }
  - { role: ansible-role-nhc, tags: [ 'nhc', 'slurm' ] }
  - { role: ansible-role-nhc-scripts, tags: [ 'nhc', 'slurm', 'nhc-scripts' ] }
  - { role: ansible-role-slurm, tags: [ 'slurm' ] }
  - { role: ansible-role-cvmfs, tags: [ 'cvmfs' ] }
  - { role: ansible-role-rdma, tags: [ 'rdma', 'infiniband' ] }
  - { role: ansible-role-system-limits, tags: [ 'limits', 'limit' ] }
  - { role: ansible-role-fgci-bash, tags: [ 'bash'] }
  - { role: ansible-role-fgci-install, tags: [ 'fgci-install', 'pull'] }
  - { role: ansible-role-dell, tags: [ 'dell' ] }
  - { role: ansible-role-smartd, tags: [ 'smartd', 'smart' ] }
  - { role: ansible-role-sshd, tags: [ 'sshd', 'ssh' ] }
  - { role: ansible-role-collectd, tags: [ 'collectd', 'monitoring' ] }
  - { role: ansible-role-serial-console, tags: [ 'serial', 'console' ] }
  - { role: ansible-role-lustre_client, tags: [ 'lustre' ], when: lustre_client_enabled }
  - { role: ansible-role-systemd-journal, tags: [ 'systemd', 'journal', 'journald' ] }
  - { role: ansible-role-lldpd, tags: [ 'lldpd', 'lldp' ] }
  - { role: ansible-role-singularity, tags: [ 'singularity' ] }

# Adding a role here? Make sure to add it to local.yml too for the role to be used with ansible-pull

- name: GPU Nodes
  hosts: compute
  strategy: free
  remote_user: root
  become: yes

  roles: 
  - { role: ansible-role-cuda, tags: [ 'cuda', 'nvidia' ] }


# Local addons to this playbook
#
- import_playbook: compute_local_play.yml
