---

# http://serverfault.com/questions/638507/how-to-access-host-variable-of-a-different-host-with-ansible
# We need some facts from the install node, specifically to find address of slurm controller.
- name: grab facts from install nodes
  hosts: production
  tasks: [ ]

- name: Compute Nodes
  hosts: compute
  remote_user: root
  sudo: yes

  roles: 
  - { role: ansible-role-fgci-repo, tags: [ 'fgci7', 'repos' ] }
  - { role: ansible-role-yum, tags: [ 'yum', 'repos', 'login' ] }
  - { role: network_interface, tags: [ 'network' ] }
  - { role: ansible-role-ntp, tags: [ 'ntp' ] }
  - { role: ansible-role-nis, tags: [ 'nis' ] }
  - { role: ansible-role-yum-cron-2, tags: [ 'yumcron' ] }
  - { role: ansible-role-rsyslog, tags: [ 'rsyslog' ] }
  - { role: ansible-role-aliases, tags: [ 'aliases', 'email' ] }
  - { role: ansible-role-nfs_mount, tags: [ 'nfsmount' ] }
  - { role: ansible-role-nhc, tags: [ 'nhc', 'slurm' ] }
  - { role: ansible-role-slurm, tags: [ 'slurm' ] }
  - { role: ansible-role-cvmfs, tags: [ 'cvmfs' ] }
  - { role: ansible-role-rdma, tags: [ 'rdma', 'infiniband' ] }
  - { role: ansible-role-system-limits, tags: [ 'limits', 'limit' ] }
  - { role: ansible-role-arc-client, tags: [ 'arc', 'nordugrid' ] }
  - { role: ansible-role-fgci-bash, tags: [ 'bash'] }
  - { role: ansible-role-dell, tags: [ 'dell' ] }
  - { role: ansible-role-smartd, tags: [ 'smartd', 'smart' ] }
  - { role: ansible-role-sshd, tags: [ 'sshd', 'ssh' ] }
  - { role: ansible-role-sshd-host-keys, tags: [ 'sshd', 'ssh', 'host-keys' ] }
  - { role: ansible-role-collectd, tags: [ 'collectd', 'monitoring' ] }
  - { role: ansible-role-serial-console, tags: [ 'serial', 'console' ] }
  - { role: ansible-role-flowdock, tags: [ 'flowdock' ] }
  - { role: ansible-role-autofs, tags: [ 'autofs' ] }
  - { role: ansible-role-adauth, tags: [ 'auth' ] }
  - { role: ansible-role-pam, tags: [ 'auth' ] }
  - { role: ansible-role-lustre_client, tags: [ 'lustre' ] }

# Adding a role here? Make sure to add it to local.yml too for the role to be used with ansible-pull

- name: GPU Nodes
  hosts: compute
  remote_user: root
  sudo: yes

  roles: 
  - { role: ansible-role-cuda, tags: [ 'cuda', 'nvidia' ] }
