---

- name: First add users to install node as root
  hosts: install
  remote_user: root

  roles: 
  - { role: ansible-role-users, tags: [ 'users', 'admin-users', 'user' ] }
  - { role: ansible-role-fgci-install, tags: [ 'fgci-install', 'gitmirror' ] }

- name: Install Node
  hosts: install
  become: yes
  vars:
    gitmirror_generate_config: False

  roles: 
  - { role: watermark-release, tags: [ 'always' ]  } 
  - { role: ansible-role-fgci-repo, tags: [ 'fgci7', 'repos' ] }
  - { role: ansible-role-yum, tags: [ 'yum', 'repos' ] }
  - { role: ansible-role-ohpc-repo, tags: [ 'yum', 'repos', 'ohpc' ] }
  - { role: ansible-role-ferm-firewall, tags: [ 'firewall', 'network' ] }
  - { role: network_interface, tags: [ 'network' ] }
  - { role: ip_forwarder, tags: [ 'network' ], 
    when: internal_interface is defined and
          external_interface is defined and
          internal_net is defined and
          internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: ansible-role-chrony, tags: [ 'ntp', 'chrony' ] }
  - { role: ansible-role-autofs, tags: [ 'autofs' ] }
  - { role: ansible-role-nis, tags: [ 'nis' ] }
  - { role: ansible-role-nsswitch, tags: [ 'nsswitch', 'auth' ] }
  - { role: ansible-role-pxe_bootstrap, tags: [ 'pxe_bootstrap', 'pxe' ] }
  - { role: ansible-role-dhcp_server, tags: [ 'dhcp_server', 'dhcpserver', 'pxe' ] }
  - { role: ansible-role-dnsmasq, tags: [ 'dnsmasq', 'pxe' ] }
  - { role: dns, tags: [ 'dns' ] }
  - { role: ansible-role-pxe_config, tags: [ 'pxe_config', 'pxe' ] }
  - { role: ansible-role-yum-cron-2, tags: [ 'yumcron' ] }
  - { role: ansible-role-rsyslog, tags: [ 'rsyslog' ] }
  - { role: ansible-role-open-vm-tools, tags: ['open-vm-tools'] }
  - { role: ansible-role-slurm, tags: [ 'slurm' ] }
  - { role: ansible-role-aliases, tags: [ 'aliases', 'email' ] }
  - { role: ansible-role-collectd, tags: [ 'collectd', 'monitoring' ] }
  - { role: ansible-role-sshd, tags: [ 'sshd', 'ssh' ] }
  - { role: ansible-role-postfix, tags: [ 'postfix', 'mail' ] }
  - { role: ansible-role-pdsh-genders, tags: [ 'pdsh', 'genders' ] }
  - { role: ansible-role-adauth, tags: [ 'auth' ] }
  - { role: ansible-role-gitmirror, tags: [ 'gitmirror'] }
  - { role: ansible-role-idmapd, tags: [ 'idmapd'] }
  - { role: ansible-role-systemd-journal, tags: [ 'systemd', 'journal', 'journald' ] }
 
- name: grab facts from production nodes
  hosts: production
  tasks: [ ]
  gather_facts: yes

- name:  Configure Admin Node After Install node
  hosts: admin
  become: yes

  roles:
  - { role: dns, tags: [ 'dns' ] }
  - { role: ansible-role-collectd, tags: [ 'collectd', 'monitoring' ] }



# Local addons to this playbook
#
- import_playbook: install_local_play.yml
