---

- name: First add users to install node as root
  hosts: install
  remote_user: root
#  sudo: yes

  roles: 
  - { role: ansible-role-users, tags: [ 'users', 'admin-users', 'user' ] }


- name: Install Node
  hosts: install
  sudo: yes

  roles: 
  - { role: ansible-role-yum, tags: [ 'yum', 'repos' ] }
  - { role: ansible-role-ferm-firewall, tags: [ 'firewall' ] }
  - { role: network_interface, tags: [ 'network' ] }
  - { role: ip_forwarder, tags: [ 'network' ], 
    when: internal_interface is defined and
          external_interface is defined and
          internal_net is defined and
          internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: ansible-role-fgci-install, tags: [ 'fgci-install' ] }
  - { role: dns, tags: [ 'dns' ] }
  - { role: ansible-role-ntp, tags: [ 'ntp' ] }
  - { role: ansible-role-pxe_bootstrap, tags: [ 'pxe_bootstrap' ] }
  - { role: ansible-role-dhcp_server, tags: [ 'dhcp_server' ] }
  - { role: ansible-role-yum-cron, tags: [ 'yumcron' ] }
  - { role: ansible-role-rsyslog, tags: [ 'rsyslog' ] }
  - { role: ansible-role-slurm, tags: [ 'slurm' ] }
  - { role: ansible-role-aliases, tags: [ 'aliases', 'email' ] }
  - { role: ansible-role-collectd, tags: [ 'collectd', 'monitoring' ] }
  - { role: ansible-role-flowdock, tags: [ 'flowdock' ] }
