---
- name: Install Node
  hosts: install
  remote_user: root
#  sudo: yes

  roles: 
  - { role: ansible-role-fgci-install, tags: [ 'install' ] }
  - { role: network_interface, tags: [ 'network' ], 
    when: internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: ip_forwarder, tags: [ 'network' ],
    when: internal_interface is defined and
          external_interface is defined and
          internal_net is defined and
          internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: dns, tags: [ 'dns' ] }
  - { role: ansible-role-ntp, tags: [ 'ntp' ] }
  - { role: ansible-role-pxe_bootstrap, tags: [ 'pxe_bootstrap' ] }
  - { role: ansible-role-dhcp_server, tags: [ 'dhcp_server' ] }
  - { role: ansible-role-yum-cron, tags: [ 'yumcron' ] }
  - { role: ansible-role-users, tags: [ 'users' ] }
  - { role: ansible-role-rsyslog-client, tags: [ 'rsyslog-client' ] }
