---

# http://serverfault.com/questions/638507/how-to-access-host-variable-of-a-different-host-with-ansible
# We need some facts from the install node, specifically to find address of slurm controller.
- name: grab facts from production nodes
  hosts: production
  tasks: [ ]

- name: NFS Node
  hosts: nfs
  remote_user: root
  become: yes

  roles: 
  - { role: network_interface, tags: [ 'network' ] }
  - { role: ansible-role-fgci-repo, tags: [ 'fgci7', 'repos' ] }
  - { role: ansible-role-yum, tags: [ 'yum', 'repos', 'login' ] }
  - { role: ansible-role-ferm-firewall, tags: [ 'firewall', 'network' ] }
  - { role: dns, tags: [ 'dns' ] }
  - { role: ansible-role-ntp, tags: [ 'ntp' ] }
  - { role: ansible-role-yum-cron-2, tags: [ 'yumcron' ] }
  - { role: ansible-role-rsyslog, tags: [ 'rsyslog' ] }
  - { role: ansible-role-nis, tags: [ 'nis' ] }
  - { role: ansible-role-aliases, tags: [ 'aliases', 'email' ] }
  - { role: ansible-role-smartd, tags: [ 'smartd' ] }
  - { role: ansible-role-idmapd, tags: [ 'idmapd' ] }
  - { role: ansible-role-nfs, tags: [ 'nfs' ] }
#  - { role: ansible-role-cvmfs, tags: [ 'cvmfs' ] }
  - { role: ansible-role-rdma, tags: [ 'rdma', 'infiniband' ] }
  - { role: ansible-role-dell, tags: [ 'dell' ] }
  - { role: ansible-role-collectd, tags: [ 'collectd', 'monitoring' ] }
  - { role: ansible-role-sshd, tags: [ 'sshd', 'ssh' ] }
  - { role: ansible-role-postfix, tags: [ 'postfix', 'mail' ] }
  - { role: ansible-role-flowdock, tags: [ 'flowdock' ] }

- name: Mount /home and /scratch on Install Node
  hosts: install
  become: yes

  roles: 
  - { role: ansible-role-nfs_mount, tags: [ 'nfsmount' ] }
  - { role: ansible-role-sshd-host-keys, tags: [ 'host-keys' ] }
