---
- src: https://github.com/resmo/ansible-role-ntp
  path: roles
  version: 0.4.0

- src: https://github.com/CSCfi/ansible-role-fgci-install
  path: roles
  version: v1.7.7

# called -2 because it replaces another role called ansible-role-yum-cron
- src: https://github.com/jeffwidman/ansible-yum-cron
  path: roles
  name: ansible-role-yum-cron-2
  version: f58e773036aa9e2baade8c4a33b81be08a232414

- src: https://github.com/CSCfi/ansible-role-users
  path: roles
  version: v1.7.3

- src: https://github.com/CSCfi/ansible-role-rsyslog
  path: roles
  version: v1.1.2

- src: https://github.com/CSCfi/ansible-role-dhcp_server
  path: roles
  version: v1.0.2

- src: https://github.com/CSCfi/ansible-role-pxe_bootstrap
  path: roles
  version: v1.4.0

- src: https://github.com/CSCfi/ansible-role-squid
  path: roles
  version: v1.2.1

- src: https://github.com/CSCfi/ansible-ferm-firewall
  path: roles
  name: ansible-role-ferm-firewall
  version: v1.0.1

- src: https://github.com/CSCfi/ansible-role-fail2ban
  path: roles
  version: v1.2.0

- src: https://github.com/CSCfi/ansible-role-slurm
  path: roles
  version: v1.6.2

- src: https://github.com/CSCfi/ansible-role-cvmfs
  path: roles
  version: v1.1.0

- src: https://github.com/CSCfi/ansible-aliases
  path: roles
  name: ansible-role-aliases
  version: v1.0.1

- src: https://github.com/CSCfi/ansible-role-rdma
  path: roles
  version: v1.2.1

- src: https://github.com/willshersystems/ansible-sshd
  path: roles
  name: ansible-role-sshd
  version: v0.5

- src: https://github.com/CSCfi/ansible-system-limits
  path: roles
  name: ansible-role-system-limits
  version: v1.0.1

- src: https://github.com/CSCfi/ansible-role-arc-client
  path: roles
  version: v1.3.0

- src: https://github.com/CSCfi/ansible-role-yum
  path: roles
  version: v1.4.0

- src: https://github.com/CSCfi/ansible-role-flowdock
  path: roles
  version: v1.2.6

- src: https://github.com/CSCfi/ansible-role-collectd
  path: roles
  version: v1.4.0

- src: https://github.com/CSCfi/ansible-role-pxe_config
  path: roles
  version: v1.4.3

- src: https://github.com/CSCfi/ansible-role-dnsmasq
  path: roles
  version: v1.0.1

- src: https://github.com/CSCfi/ansible-role-nis
  path: roles
  version: v1.0.1

- src: https://github.com/CSCfi/ansible-role-nfs
  path: roles
  version: v1.0.4

- src: https://github.com/CSCfi/ansible-role-nfs_mount
  path: roles
  version: v1.2.3

- src: https://github.com/CSCfi/ansible-role-arc-frontend
  path: roles
  version: v1.3.0

- src: https://github.com/CSCfi/ansible-role-fgci-bash
  path: roles
  version: v1.1.4

- src: https://github.com/CSCfi/ansible-role-cuda
  path: roles
  version: v1.5.3

- src: https://github.com/CSCfi/ansible-role-nhc
  path: roles
  version: v1.2.4

- src: https://github.com/CSCfi/ansible-role-nhc-scripts
  path: roles
  version: v1.0.0

- src: https://github.com/CSCfi/ansible-role-dell
  path: roles
  version: v1.1.1

- src: https://github.com/CSCfi/ansible-role-sshd-host-keys
  path: roles
  version: v1.0.2

- src: https://github.com/CSCfi/ansible-role-smartd
  path: roles
  version: v1.1.4

- src: https://github.com/CSCfi/ansible-role-postfix
  path: roles
  version: v1.0.0

- src: https://github.com/CSCfi/ansible-role-fgci-repo
  path: roles
  version: v1.0.0

- src: https://github.com/CSCfi/ansible-role-fgci-login
  path: roles
  version: v1.1.2

- src: https://github.com/mhakala/ansible-role-adauth
  path: roles
  version: ae40b205c857cff6bcebf7f4a37b3ca2e31ba247

- src: https://github.com/jabl/ansible-role-pdsh-genders
  path: roles
  version: 4402bca5c1d6283347048ea3c4b44cc99f16c2f1

- src: https://github.com/CSCfi/ansible-role-serial-console
  path: roles
  version: v1.0.1

- src: https://github.com/cmprescott/ansible-role-autofs
  path: roles
  name: ansible-role-autofs
  version: 0.2.2

- src: https://github.com/CSCfi/ansible-nsswitch
  path: roles
  name: ansible-role-nsswitch
  version: v1.0.0

- src: https://github.com/mhakala/ansible-role-lustre_client
  path: roles
  version: 47f1cc95587246e307f364949f467a07fb171b33

- src: https://github.com/jabl/ansible-role-pam
  path: roles
  version: v1.0.0

- src: https://github.com/jabl/ansible-role-gitmirror
  path: roles
  version: acafcaff5094b5d7f9da796096068d62ae895b85

- src: https://github.com/mhakala/ansible-role-idmapd
  path: roles
  version: 336875424c799846e455004871a77f7655c1f8c6

- src: https://github.com/mhakala/ansible-role-samba
  path: roles
  version: 9c2d2addb1112b1aad182e626f8bd87e5917cd78

- src: https://github.com/jabl/ansible-role-open-vm-tools
  path: roles
  version: v1.0.0

- src: https://github.com/CSCfi/ansible-systemd-journal
  path: roles
  version: v1.0.1
  name: ansible-role-systemd-journal

- src: https://github.com/jabl/ansible-role-hosts-int
  path: roles
  version: v1.0.2

- src: https://github.com/CSCfi/ansible-role-chrony
  path: roles
  version: v1.1.1

- src: https://github.com/CSCfi/ansible-lldpd
  path: roles
  version: v1.1.2
  name: ansible-role-lldpd

- src: https://github.com/CSCfi/ansible-role-singularity
  path: roles
  version: v1.0.1
