---
- src: https://github.com/resmo/ansible-role-ntp
  path: roles
  version: 0.4.0

- src: https://github.com/fgci-org/ansible-role-fgci-install
  path: roles
  version: v1.9.0

# called -2 because it replaces another role called ansible-role-yum-cron
- src: https://github.com/jeffwidman/ansible-yum-cron
  path: roles
  name: ansible-role-yum-cron-2
  version: 218e3140ac5da05eddbc277d3aebc177ab59c7b0

- src: https://github.com/CSCfi/ansible-role-users
  path: roles
  version: v1.9.1

- src: https://github.com/CSCfi/ansible-role-rsyslog
  path: roles
  version: v1.1.9

- src: https://github.com/CSCfi/ansible-role-dhcp_server
  path: roles
  version: v1.0.2

- src: https://github.com/CSCfi/ansible-role-pxe_bootstrap
  path: roles
  version: v1.4.6

- src: https://github.com/CSCfi/ansible-role-squid
  path: roles
  version: v1.3.4

- src: https://github.com/CSCfi/ansible-ferm-firewall
  path: roles
  name: ansible-role-ferm-firewall
  version: v1.3.0

- src: https://github.com/fgci-org/ansible-role-nftables
  path: roles
  name: ansible-role-nftables
  version: v1.0

- src: https://github.com/CSCfi/ansible-role-fail2ban
  path: roles
  version: v1.3.2

- src: https://github.com/fgci-org/ansible-role-slurm
  path: roles
  version: v2.1.3

- src: https://github.com/CSCfi/ansible-role-cvmfs
  path: roles
  version: v1.2.5

- src: https://github.com/CSCfi/ansible-aliases
  path: roles
  name: ansible-role-aliases
  version: v1.0.4

- src: https://github.com/fgci-org/ansible-role-rdma
  path: roles
  version: v1.4.2

- src: https://github.com/willshersystems/ansible-sshd
  path: roles
  name: ansible-role-sshd
  version: v0.8.3

- src: https://github.com/CSCfi/ansible-system-limits
  path: roles
  name: ansible-role-system-limits
  version: v1.1.2

- src: https://github.com/CSCfi/ansible-role-arc-client
  path: roles
  version: v1.5.7

- src: https://github.com/fgci-org/ansible-role-yum
  path: roles
  version: v1.5.8

- src: https://github.com/fgci-org/ansible-role-collectd
  path: roles
  version: v2.1.5

- src: https://github.com/CSCfi/ansible-role-pxe_config
  path: roles
  version: v1.6.4

- src: https://github.com/CSCfi/ansible-role-dnsmasq
  path: roles
  version: v1.0.1

- src: https://github.com/CSCfi/ansible-role-nis
  path: roles
  version: v1.1.3

- src: https://github.com/fgci-org/ansible-role-nfs
  path: roles
  version: v1.2.2

- src: https://github.com/CSCfi/ansible-role-nfs_mount
  path: roles
  version: v1.3.2

- src: https://github.com/fgci-org/ansible-role-fgci-bash
  path: roles
  version: v1.3.1

- src: https://github.com/fgci-org/ansible-role-cuda
  path: roles
  version: v1.7.4

- src: https://github.com/CSCfi/ansible-role-nhc
  path: roles
  version: v1.3.7

- src: https://github.com/CSCfi/ansible-role-nhc-scripts
  path: roles
  version: v1.0.3

- src: https://github.com/CSCfi/ansible-role-dell
  path: roles
  version: v1.2.0

- src: https://github.com/CSCfi/ansible-role-sshd-host-keys
  path: roles
  version: v1.1.4

- src: https://github.com/CSCfi/ansible-role-smartd
  path: roles
  version: v1.2.3

- src: https://github.com/CSCfi/ansible-role-postfix
  path: roles
  version: v1.1.4

- src: https://github.com/CSCfi/ansible-role-fgci-repo
  path: roles
  version: v1.0.0

- src: https://github.com/CSCfi/ansible-role-fgci-login
  path: roles
  version: v1.1.3

- src: https://github.com/mhakala/ansible-role-adauth
  path: roles
  version: v1.0

- src: https://github.com/fgci-org/ansible-role-pdsh-genders
  path: roles
  version: v1.3.4

- src: https://github.com/CSCfi/ansible-role-serial-console
  path: roles
  version: v1.1.1

- src: https://github.com/cmprescott/ansible-role-autofs
  path: roles
  name: ansible-role-autofs
  version: 1.0.0

- src: https://github.com/CSCfi/ansible-nsswitch
  path: roles
  name: ansible-role-nsswitch
  version: v1.0.1

- src: https://github.com/fgci-org/ansible-role-lustre_client
  path: roles
  version: v1.2.2

- src: https://github.com/fgci-org/ansible-role-pam
  path: roles
  version: v1.0.3

- src: https://github.com/fgci-org/ansible-role-gitmirror
  path: roles
  version: v1.0.1

- src: https://github.com/mhakala/ansible-role-idmapd
  path: roles
  version: 0b48d86318da6e303e76359a593f5195076f3021

- src: https://github.com/AaltoScienceIT/ansible-role-samba
  path: roles
  version: v1.0.1

- src: https://github.com/fgci-org/ansible-role-open-vm-tools
  path: roles
  version: v1.0.1

- src: https://github.com/CSCfi/ansible-systemd-journal
  path: roles
  version: v1.0.2
  name: ansible-role-systemd-journal

- src: https://github.com/fgci-org/ansible-role-hosts-int
  path: roles
  version: v1.0.4

- src: https://github.com/CSCfi/ansible-role-chrony
  path: roles
  version: v1.1.6

- src: https://github.com/CSCfi/ansible-lldpd
  path: roles
  version: v1.1.6
  name: ansible-role-lldpd

- src: https://github.com/CSCfi/ansible-role-singularity
  path: roles
  version: v1.0.5

- src: https://github.com/fgci-org/ansible-role-ohpc-repo
  path: roles
  version: v0.1

- src: https://github.com/AaltoScienceIT/ansible-role-ohpc-setup
  path: roles

- src: https://github.com/AaltoScienceIT/ansible-role-ohpc-provision
  path: roles

- src: https://github.com/AaltoScienceIT/ansible-role-sacct_gpu
  path: roles

- src: https://github.com/AaltoScienceIT/ansible-role-fgci-ssh-keys
  path: roles
