---
#
# This role will reboot all compute nodes
#

- name: Reboot Compute Nodes
  hosts: compute
  remote_user: root
  gather_facts: false 
  
  tasks:
  - name: Reboot compute nodes
    shell: sleep 2 && /sbin/shutdown -r now "Ansible reboot"
    async: 1
    pool: 0
    ignore_errors: true

