---
#
# This role will shutdown all nodes
#

- name: Shutdown Compute Nodes
  hosts: compute
  remote_user: root
  gather_facts: false 
  
  tasks:
  - name: Shutdown compute nodes
    shell: sleep 2 && /sbin/shutdown -h now "Ansible shutdown"
    async: 1
    poll: 0
    ignore_errors: true

- name: Shutdown Compute Nodes
  hosts: [ grid, install, login, nfs, admin ]
  remote_user: root
  gather_facts: false 
  
  tasks:
  - name: Shutdown the rest of the nodes
    shell: sleep 2 && /sbin/shutdown -h now "Ansible shutdown"
    async: 1
    poll: 0
    ignore_errors: true
